FROM node:20-alpine

WORKDIR /app

# Instalar pnpm globalmente
RUN npm install -g pnpm nodemon

# Copiar os arquivos de configuração
COPY package*.json ./

# Instalar todas as dependências, incluindo as de desenvolvimento
RUN pnpm install

# Não precisamos copiar o código fonte aqui, pois usaremos volumes para desenvolvimento
# O volume será montado em tempo de execução

# Expor a porta que a aplicação utilizará
EXPOSE 3001

# Comando para iniciar a aplicação em modo de desenvolvimento com hot-reloading
CMD ["pnpm", "run", "dev"]