apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-manager
data:
  NODE_ENV: "production"
  PORT: "3001"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskmanager"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: task-manager
type: Opaque
data:
  # postgres em base64
  DB_USER: cG9zdGdyZXM=
  # postgres em base64
  DB_PASSWORD: cG9zdGdyZXM=